# Generated by Django 3.1.2 on 2021-06-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(default='Hi', max_length=160)),
                ('name_intro', models.CharField(default="I'm", max_length=160)),
                ('name', models.CharField(default='Arindam', max_length=50)),
                ('profession', models.CharField(default='Web Developer', max_length=160)),
            ],
        ),
    ]
