# Generated by Django 3.1.2 on 2021-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='fb',
            field=models.CharField(default='https://www.facebook.com/ar58p/', max_length=264),
        ),
        migrations.AddField(
            model_name='intro',
            name='github',
            field=models.CharField(default='https://www.facebook.com/ar58p/', max_length=264),
        ),
        migrations.AddField(
            model_name='intro',
            name='linked_in',
            field=models.CharField(default='https://www.facebook.com/ar58p/', max_length=264),
        ),
    ]
