# Generated by Django 3.1.2 on 2021-06-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210602_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Arindam Here,', max_length=260)),
                ('text', models.TextField(default=' ')),
            ],
        ),
    ]
