# Generated by Django 3.1.2 on 2021-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210602_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='greetings',
            field=models.CharField(max_length=160),
        ),
    ]
