# Generated by Django 3.1.2 on 2021-06-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210602_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='head_image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
