# Generated by Django 3.1.2 on 2021-06-02 08:27

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_intro_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='head_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='media'),
        ),
    ]
