# Generated by Django 3.1.2 on 2021-06-02 08:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20210602_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='head_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
