# Generated by Django 3.1.2 on 2021-06-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20210602_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
