# Generated by Django 3.1.2 on 2021-06-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
