# Generated by Django 3.1.2 on 2021-06-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20210602_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(default='Arindam Here,', max_length=260),
        ),
    ]
