# Generated by Django 3.1.2 on 2021-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20210602_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professiona Skills', max_length=260)),
                ('text', models.TextField(default=' ')),
            ],
        ),
    ]
