# Generated by Django 3.1.2 on 2021-06-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='Professional Skills', max_length=260),
        ),
    ]
