# Generated by Django 3.1.2 on 2021-06-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_auto_20210602_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
