# Generated by Django 3.1.2 on 2021-06-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='profession',
        ),
    ]
