# Generated by Django 3.1.2 on 2021-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_remove_intro_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('instagram', models.CharField(max_length=260)),
                ('twitter', models.CharField(max_length=260)),
            ],
        ),
    ]
