# Generated by Django 3.1.2 on 2021-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.TextField(default=' '),
        ),
    ]
