# Generated by Django 3.1.2 on 2021-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_footer_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
