# Generated by Django 3.1.2 on 2021-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0026_auto_20210602_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
